theme: jekyll-theme-leap-day

show_downloads: true
google_analytics: UA-109329008-1 

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-avatar
   - jekyll-seo-tag
   - jekyll-include-cache

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
